#!/bin/bash

# this is a simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

# ==================
# Background & Conky
# ==================

# Background/wallpaper
#xsetroot -solid '#5A8E3A'
feh --bg-scale /home/cam/pictures/wallpapers/somefield-walking-octopus.png

# Pad the top of the screen (room for conky)
# Taken care of in panel scripts
#hc pad 0 15 0 0 0
#conky -c conkyrc-herbstluft


# ===========
# Keybindings
# ===========

# remove all existing keybindings
hc keyunbind --all

Mod=Mod4

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

# Program launchers
hc keybind $Mod-t spawn urxvt
hc keybind $Mod-b spawn google-chrome
hc keybind $Mod-F2 spawn dmenu_run -b -i #-nb '#1e1e1e' -nf '#888888' -sb '#FFFF84' -sf '#1e1e1e'
#hc keybind $Mod-Return spawn dmenu_run -b -f -i -fn "-*-ubuntu-medium-*-*-*-14-*-*-*-*-*-*-*"
hc keybind $Mod-Return spawn dmenu_run -b -f -i -fn "xft:ubuntu:size=11"


# tags

TAG_NAMES=( {1..9} )
TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
#hc keybind $Mod-Right use_index +1 --skip-visible
#hc keybind $Mod-Left  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-v split vertical 0.5
hc keybind $Mod-Shift-v split vertical 0.3
hc keybind $Mod-h split horizontal 0.5
hc keybind $Mod-Shift-h split horizontal 0.3
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-Left resize left +$RESIZESTEP
hc keybind $Mod-Control-Down resize down +$RESIZESTEP
hc keybind $Mod-Control-Up resize up +$RESIZESTEP
hc keybind $Mod-Control-Right resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-Left focus left
hc keybind $Mod-Down focus down
hc keybind $Mod-Up focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Down shift down
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-Right shift right

# ======
# Colors
# ======
hc set frame_border_active_color '#333333'
hc set frame_border_normal_color '#1F1F1F'
hc set frame_bg_normal_color '#CCCCCC'
hc set frame_bg_active_color '#666666'
hc set frame_border_width 1
hc set window_border_width 1
hc set window_border_normal_color '#666666'
hc set window_border_active_color '#3700FF'
hc set always_show_frame 1
hc set window_gap 4
hc set frame_bg_transparent '1'

# =====
# Rules
# =====
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
#hc rule focus=off # normally do not focus new clients
hc rule focus=on
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc remove_monitor 1
# hc move_monitor 0 1280x1024+0+0
# hc add_monitor 1280x1024+1280+0

# ==============
# find the panel
# ==============
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    $panel $monitor &
done

